version: '3.9'

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/timeless:ro
      - ./data:/timeless/data:rw
      - ./config:/timeless/config:rw
  
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  internal_net:
    driver: bridge

volumes:
  postgres_data: